name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
      
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
     name: dev
    needs: build
    steps:
    - name: Run a one-line script
      run: echo deploy dev
      
  deploy-front:
    runs-on: ubuntu-latest
    environment:
      name: front
    needs: deploy-dev
    steps:
    - name: Run a one-line script
      run: echo deploy front
      
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: deploy-front
    steps:
    - name: Run a one-line script
      run: echo deploy prd
